# La\CoreBundle\Resources\config\serializer\Model.User.yml
FOS\UserBundle\Model\User:
    exclusion_policy: ALL
    properties:
        username:
            expose: true
        id:
            expose: true
        roles:
            expose: true