security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        La\CoreBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]
        in_memory:
            memory:
                users:
                    ryan:  { password: ryanpass, roles: 'ROLE_USER' }
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        user_db:
            entity: {class: La\CoreBundle\Entity\User, property: email}

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js|sandbox)/
            security: false
        login_firewall:
            pattern:   ^/login$
            anonymous: ~
        register_firewall:
            pattern:   ^/register$
            anonymous: ~
        secured_area:
            pattern: ^/
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: /
            logout:
                path:   /logout
                target: /

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/_wdt, roles: 'IS_AUTHENTICATED_ANONYMOUSLY' }
