services:
    la_core.repository.action:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:Action]

    la_core.repository.answer:
            class: Doctrine\ORM\EntityRepository
            factory_service: doctrine.orm.entity_manager
            factory_method: getRepository
            arguments: [LaCoreBundle:Answer]

    la_core.repository.url_content:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:UrlContent]

    la_core.third_party.sebastian_version:
        class: SebastianBergmann\Version
        arguments: ['0.0.0', %kernel.root_dir%/..]
