parameters:
    la_core.repository.action.class: Doctrine\ORM\EntityRepository
    la_core.repository.url_content.class: Doctrine\ORM\EntityRepository

services:
    la_core.repository.action:
        class: %la_core.repository.action.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:Action]

    la_core.repository.url_content:
        class: %la_core.repository.url_content.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:UrlContent]

    la_core.third_party.sebastian_version:
        class: SebastianBergmann\Version
        arguments: ['0.0.0', %kernel.root_dir%/..]
