services:
    la_core.repository.learning_entity:
        class: La\CoreBundle\Entity\Repository\LearningEntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:LearningEntity]

    la_core.repository.agora:
        class: La\CoreBundle\Entity\Repository\AgoraRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:Agora]

    la_core.repository.objective:
        class: La\CoreBundle\Entity\Repository\ObjectiveRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:Objective]

    la_core.repository.action:
        class: La\CoreBundle\Entity\Repository\ActionRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:Action]

    la_core.repository.affinity:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:Affinity]

    la_core.repository.progress:
        class: La\CoreBundle\Entity\Repository\ProgressRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:Progress]

    la_core.repository.answer:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:Answer]

    la_core.repository.url_content:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:UrlContent]

    la_core.repository.progress:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:Progress]

    la_core.third_party.sebastian_version:
        class: SebastianBergmann\Version
        arguments: ['0.0.0', %kernel.root_dir%/..]
