services:
    la_core.repository.user:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:User]

    la_core.repository.learning_entity:
        class: La\CoreBundle\Entity\Repository\LearningEntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:LearningEntity]

    la_core.repository.techne:
        class: La\CoreBundle\Entity\Repository\TechneRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:Techne]

    la_core.repository.agora:
        class: La\CoreBundle\Entity\Repository\AgoraRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:Agora]

    la_core.repository.agora_base:
        class: La\CoreBundle\Entity\Repository\AgoraBaseRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:AgoraBase]

    la_core.repository.objective:
        class: La\CoreBundle\Entity\Repository\ObjectiveRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:Objective]

    la_core.repository.action:
        class: La\CoreBundle\Entity\Repository\ActionRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:Action]

    la_core.repository.progress:
        class: La\CoreBundle\Entity\Repository\ProgressRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:Progress]

    la_core.repository.answer:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:Answer]

    la_core.repository.outcome:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:Outcome]

    la_core.repository.trace:
        class: La\CoreBundle\Entity\Repository\TraceRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:Trace]

    la_core.repository.url_content:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:UrlContent]

    la_core.repository.simple_url_question:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:SimpleUrlQuestion]

    la_core.repository.content:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:Content]

    la_core.repository.progress:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:Progress]

    la_core.repository.user:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:User]

    la_core.repository.goal:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:Goal]

    la_core.repository.agora_goal:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:AgoraGoal]

    la_core.repository.user_probability:
        class: La\CoreBundle\Entity\Repository\UserProbabilityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:UserProbability]

    la_core.repository.event:
        class: La\CoreBundle\Entity\Repository\EventRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:Event]

    la_core.repository.user_probability_event:
        class: La\CoreBundle\Entity\Repository\UserProbabilityEventRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:UserProbabilityEvent]

    la_core.repository.user_trace_event:
        class: La\CoreBundle\Entity\Repository\UserTraceEventRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:UserTraceEvent]

    la_core.repository.outcome_probability:
        class: La\CoreBundle\Entity\Repository\OutcomeProbabilityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:OutcomeProbability]

    la_core.repository.profile:
        class: La\CoreBundle\Entity\Repository\ProfileRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LaCoreBundle:Profile]

    la_core.third_party.sebastian_version:
        class: SebastianBergmann\Version
        arguments: ['0.0.0', %kernel.root_dir%/..]
