La\CoreBundle\Entity\UrlContent:
    properties:
        instruction:
            - NotBlank: ~
            - NotNull: ~
        url:
            - NotBlank: ~
            - NotNull: ~
            - Url: ~
