la_learnodex_api_random_card:
    pattern: /cards/random
    defaults: { _controller: LaLearnodexBundle:Api/Card:randomCard, _format: ~ }
    requirements:
        _method: GET
    options:
        expose: true

la_learnodex_api_trace:
    pattern: /trace/{userId}/{outcomeId}
    defaults: { _controller: LaLearnodexBundle:Api/Trace:trace, _format: ~ }
    requirements:
        _method: POST
    options:
        expose: true

la_learnodex_api_goal_agora:
    pattern: /goal/create/agora/{id}
    defaults: { _controller: LaLearnodexBundle:Api/Goal:createAgoraGoal, _format: ~ }
    requirements:
        _method: POST
    options:
        expose: true

la_learnodex_api_goal_persona:
    pattern: /goal/create/persona/{id}
    defaults: { _controller: LaLearnodexBundle:Api/Goal:createPersonaGoal, _format: ~ }
    requirements:
        _method: POST
    options:
        expose: true
