homepage:
    path:     /
    defaults: { _controller: LaLearnodexBundle:Default:index }

register:
    path:     /register
    defaults: { _controller: LaLearnodexBundle:User:register }
login:
    path:     /login
    defaults: { _controller: LaLearnodexBundle:User:login }
login_check:
    path:     /login_check
logout:
    path:     /logout

new_card:
    path:     /c/{type}
    defaults: { _controller: LaLearnodexBundle:Card:index }
card:
    path:     /c/{type}/{id}
    defaults: { _controller: LaLearnodexBundle:Card:index }
card_outcome:
    path:     /c/{type}/{id}/outcome
    defaults: { _controller: LaLearnodexBundle:Card:outcome }
card_link:
    path:     /c/{type}/{id}/link
    defaults: { _controller: LaLearnodexBundle:Card:link }
add_outcome:
    path:     /addoutcome/{type}/{id}
    defaults: { _controller: LaLearnodexBundle:Card:addOutcome }
