register:
    path:     /register
    defaults: { _controller: LaLearnodexBundle:User:register }
login:
    path:     /login
    defaults: { _controller: LaLearnodexBundle:User:login }
login_check:
    path:     /login_check
logout:
    path:     /logout

homepage:
    path:     /
    defaults: { _controller: LaLearnodexBundle:Default:index }
card_auto:
    path:     /card
    defaults: { _controller: LaLearnodexBundle:Default:card }
card:
    path:     /card/{id}
    defaults: { _controller: LaLearnodexBundle:Default:card }

admin_homepage:
    path:     /admin
    defaults: { _controller: LaLearnodexBundle:Admin:index }
new_card:
    path:     /new/{type}
    defaults: { _controller: LaLearnodexBundle:Admin:new }
card_name:
    path:     /name/{id}
    defaults: { _controller: LaLearnodexBundle:Admin:name }
card_content_select:
    path:     /content/select/{id}
    defaults: { _controller: LaLearnodexBundle:Admin:selectContent }
card_content_selected:
    path:     /content/select/{id}/{type}
    defaults: { _controller: LaLearnodexBundle:Admin:selectContent }
card_content:
    path:     /content/{id}
    defaults: { _controller: LaLearnodexBundle:Admin:content }
add_answer:
    path:     /addAnswer/{id}
    defaults: { _controller: LaLearnodexBundle:Admin:addAnswer }
remove_answer:
    path:     /removeAnswer/{id}/{answerId}
    defaults: { _controller: LaLearnodexBundle:Admin:removeAnswer }
card_outcome:
    path:     /entity/{id}/outcome
    defaults: { _controller: LaLearnodexBundle:Admin:outcome }
add_outcome:
    path:     /addoutcome/{id}
    defaults: { _controller: LaLearnodexBundle:Admin:addOutcome }
remove_outcome:
    path:     /removeoutcome/{outcomeId}
    defaults: { _controller: LaLearnodexBundle:Admin:removeOutcome }

card_link:
    path:     /entity/{id}/link
    defaults: { _controller: LaLearnodexBundle:Admin:link }
add_child:
    path:     /addChild/{parentId}/{childId}
    defaults: { _controller: LaLearnodexBundle:Admin:addChild }
