homepage:
    path:     /
    defaults: { _controller: LaLearnodexBundle:Default:index }

register:
    path:     /register
    defaults: { _controller: LaLearnodexBundle:User:register }
login:
    path:     /login
    defaults: { _controller: LaLearnodexBundle:User:login }
login_check:
    path:     /login_check
logout:
    path:     /logout

new_card:
    path:     /new/{type}
    defaults: { _controller: LaLearnodexBundle:Card:new }
card:
    path:     /entity/{id}
    defaults: { _controller: LaLearnodexBundle:Card:index }
card_outcome:
    path:     /entity/{id}/outcome
    defaults: { _controller: LaLearnodexBundle:Card:outcome }
add_outcome:
    path:     /addoutcome/{id}
    defaults: { _controller: LaLearnodexBundle:Card:addOutcome }
update_outcome:
    path:     /updateoutcome/{outcomeId}
    defaults: { _controller: LaLearnodexBundle:Card:updateOutcome }
remove_outcome:
    path:     /removeoutcome/{outcomeId}
    defaults: { _controller: LaLearnodexBundle:Card:removeOutcome }

card_link:
    path:     /entity/{id}/link
    defaults: { _controller: LaLearnodexBundle:Card:link }
add_child:
    path:     /addChild/{parentId}/{childId}
    defaults: { _controller: LaLearnodexBundle:Card:addChild }
