homepage:
    path:     /
    defaults: { _controller: LaLearnodexBundle:Default:index }
card_auto:
    path:     /card
    defaults: { _controller: LaLearnodexBundle:Default:card }
card:
    path:     /card/{id}
    defaults: { _controller: LaLearnodexBundle:Default:card }
make_trace:
    path:     /trace/{outcomeId}
    defaults: { _controller: LaLearnodexBundle:Trace:trace }
button_trace:
    path:     /buttontrace/{id}/{caption}
    defaults: { _controller: LaLearnodexBundle:Trace:traceButton }
url_trace:
    path:     /urltrace/{id}
    defaults: { _controller: LaLearnodexBundle:Trace:traceUrl }
dna:
    path:     /dna
    defaults: { _controller: LaLearnodexBundle:Default:dna }
remove_all_my_traces:
    path:     /removeallmytraces
    defaults: { _controller: LaLearnodexBundle:Trace:removeMyTraces }

admin_homepage:
    path:     /admin
    defaults: { _controller: LaLearnodexBundle:Admin:index }
new_card:
    path:     /new/{type}
    defaults: { _controller: LaLearnodexBundle:Admin:new }
card_name:
    path:     /name/{id}
    defaults: { _controller: LaLearnodexBundle:Admin:name }
card_content_select:
    path:     /content/select/{id}
    defaults: { _controller: LaLearnodexBundle:Admin:selectContent }
card_content_selected:
    path:     /content/select/{id}/{type}
    defaults: { _controller: LaLearnodexBundle:Admin:selectContent }
card_content:
    path:     /content/{id}
    defaults: { _controller: LaLearnodexBundle:Admin:content }
add_answer:
    path:     /addAnswer/{id}
    defaults: { _controller: LaLearnodexBundle:Admin:addAnswer }
remove_answer:
    path:     /removeAnswer/{id}/{answerId}
    defaults: { _controller: LaLearnodexBundle:Admin:removeAnswer }
card_outcome:
    path:     /entity/{id}/outcome
    defaults: { _controller: LaLearnodexBundle:Admin:outcome }
add_outcome:
    path:     /addoutcome/{id}
    defaults: { _controller: LaLearnodexBundle:Admin:addOutcome }
set_outcome_affinity:
    path:     /setoutcomeaffinity/{outcomeId}/{affinity}
    defaults: { _controller: LaLearnodexBundle:Admin:setOutcomeAffinity }
set_outcome_progress:
    path:     /setoutcomeprogress/{outcomeId}/{progress}
    defaults: { _controller: LaLearnodexBundle:Admin:setOutcomeProgress }
remove_outcome:
    path:     /removeoutcome/{outcomeId}
    defaults: { _controller: LaLearnodexBundle:Admin:removeOutcome }
add_result:
    path:     /addresult/{id}/{outcomeId}
    defaults: { _controller: LaLearnodexBundle:Admin:addResult }
set_result:
    path:     /setresult/{resultId}/{value}
    defaults: { _controller: LaLearnodexBundle:Admin:setResult }
remove_result:
    path:     /removeresult/{resultId}
    defaults: { _controller: LaLearnodexBundle:Admin:removeResult }

card_link:
    path:     /entity/{id}/link
    defaults: { _controller: LaLearnodexBundle:Admin:link }
add_link:
    path:     /addLink/{id}/{parentId}/{childId}
    defaults: { _controller: LaLearnodexBundle:Admin:addLink }
edit_link:
    path:     /editLink/{id}/{linkId}
    defaults: { _controller: LaLearnodexBundle:Admin:editLink }
remove_link:
    path:     /removeLink/{id}/{linkId}
    defaults: { _controller: LaLearnodexBundle:Admin:removeLink }

persona_homepage:
    path:     /persona
    defaults: { _controller: LaLearnodexBundle:Persona:index }
persona_create:
    path:     /persona/create
    defaults: { _controller: LaLearnodexBundle:Persona:edit }
persona_edit:
    path:     /persona/edit/{id}
    defaults: { _controller: LaLearnodexBundle:Persona:edit }
persona_affinity:
    path:     /persona/affinity/{id}
    defaults: { _controller: LaLearnodexBundle:Persona:affinity }
persona_remove_affinity:
    path:     /persona/remove_affinity/{personaId}/{id}
    defaults: { _controller: LaLearnodexBundle:Persona:removeAffinity }
persona_compare:
    path:     /persona/compare/{id}
    defaults: { _controller: LaLearnodexBundle:Persona:compare }

goal_create_agora:
    path:     /goal/create/agora/{id}
    defaults: { _controller: LaLearnodexBundle:Goal:createAgoraGoal }
goal_create_persona:
    path:     /goal/create/persona/{id}
    defaults: { _controller: LaLearnodexBundle:Goal:createPersonaGoal }
goal_open:
    path:     /goal/open/{id}
    defaults: { _controller: LaLearnodexBundle:Goal:open }
goal_close:
    path:     /goal/close
    defaults: { _controller: LaLearnodexBundle:Goal:close }


new_database:
    path:     /newdb
    defaults: { _controller: LaLearnodexBundle:Import:newDatabase }
