la_learnodex_api_random_card:
    pattern: /cards/random
    defaults: { _controller: LaLearnodexBundle:Api/Card:randomCard, _format: ~ }
    requirements:
        _method: GET
    options:
        expose: true

la_learnodex_api_fixed_card:
    pattern: /cards/id/{cardId}
    defaults: { _controller: LaLearnodexBundle:Api/Card:card, _format: ~ }
    requirements:
        _method: GET
        cardId: \d+
    options:
        expose: true

la_learnodex_api_trace:
    pattern: /trace/{outcomeId}
    defaults: { _controller: LaLearnodexBundle:Api/Trace:trace, _format: ~ }
    requirements:
        _method: POST
    options:
        expose: true

la_learnodex_api_goals:
    pattern: /goals
    defaults: { _controller: LaLearnodexBundle:Api/Goal:loadAll, _format: ~ }
    requirements:
        _method: GET
    options:
        expose: true

la_learnodex_api_active_goals:
    pattern: /goals/active
    defaults: { _controller: LaLearnodexBundle:Api/Goal:loadActive, _format: ~ }
    requirements:
        _method: GET
    options:
        expose: true

la_learnodex_api_goal_agora:
    pattern: /goals/agora/{id}
    defaults: { _controller: LaLearnodexBundle:Api/Goal:createAgoraGoal, _format: ~ }
    requirements:
        _method: POST
        id: \d+
    options:
        expose: true

la_learnodex_api_goal_remove:
    pattern: /goals/{id}
    defaults: { _controller: LaLearnodexBundle:Api/Goal:remove, _format: ~ }
    requirements:
        _method: DELETE
        id: \d+
    options:
        expose: true

la_learnodex_api_goal_activate:
    pattern: /goals/{id}/activate/{activeFlag}
    defaults: { _controller: LaLearnodexBundle:Api/Goal:activate, _format: ~ }
    requirements:
        _method: PATCH
        id: \d+
        activeFlag: 0|1
    options:
        expose: true

la_learnodex_api_profile:
    pattern: /user/profile
    defaults: { _controller: LaLearnodexBundle:Api/User:loadProfile, _format: ~ }
    requirements:
        _method: GET
    options:
        expose: true

la_learnodex_api_dna:
    pattern: /user/dna
    defaults: { _controller: LaLearnodexBundle:Api/Dna:loadAll, _format: ~ }
    requirements:
        _method: GET
    options:
        expose: true

la_learnodex_api_user_techne:
    pattern: /user/techne
    defaults: { _controller: LaLearnodexBundle:Api/Techne:loadAllForUser, _format: ~ }
    requirements:
        _method: GET
    options:
        expose: true

la_learnodex_api_single_techne:
    pattern: /techne/{id}
    defaults: { _controller: LaLearnodexBundle:Api/Techne:load, _format: ~ }
    requirements:
        _method: GET
        id: \d+
    options:
        expose: true

la_learnodex_api_agora:
    pattern: /agora
    defaults: { _controller: LaLearnodexBundle:Api/Agora:loadAll, _format: ~ }
    requirements:
        _method: GET
    options:
        expose: true

la_learnodex_api_action:
    pattern: /action
    defaults: { _controller: LaLearnodexBundle:Api/Action:loadAll, _format: ~ }
    requirements:
        _method: GET
    options:
        expose: true

la_learnodex_api_techne:
    pattern: /techne
    defaults: { _controller: LaLearnodexBundle:Api/Techne:loadAll, _format: ~ }
    requirements:
        _method: GET
    options:
        expose: true

la_learnodex_api_entity_save:
    pattern: /save
    defaults: { _controller: LaLearnodexBundle:Api/Admin:save, _format: ~ }
    requirements:
        _method: POST
    options:
        expose: true

la_learnodex_api_entity_create_action:
    pattern: /create/{type}
    defaults: { _controller: LaLearnodexBundle:Api/Admin:create, _format: ~ }
    requirements:
        _method: POST
    options:
        expose: true

la_learnodex_api_entity_uplink_with_weight:
    pattern: /uplink/{childId}/{parentId}/{weight}
    defaults: { _controller: LaLearnodexBundle:Api/Admin:uplink, _format: ~ }
    requirements:
        _method: POST
    options:
        expose: true

la_learnodex_api_entity_uplink:
    pattern: /uplink/{childId}/{parentId}
    defaults: { _controller: LaLearnodexBundle:Api/Admin:uplink, _format: ~ }
    requirements:
        _method: POST
    options:
        expose: true

la_learnodex_api_entity_unlink:
    pattern: /unlink/{parentId}/{downlink}
    defaults: { _controller: LaLearnodexBundle:Api/Admin:unlink, _format: ~ }
    requirements:
        _method: POST
    options:
        expose: true
