homepage:
    path:     /
    defaults: { _controller: LaLearnodexBundle:Default:index }
card_auto:
    path:     /card
    defaults: { _controller: LaLearnodexBundle:Default:card }
card:
    path:     /card/{id}
    defaults: { _controller: LaLearnodexBundle:Default:card }
make_trace:
    path:     /trace/{outcomeId}
    defaults: { _controller: LaLearnodexBundle:Trace:trace }
button_trace:
    path:     /buttontrace/{id}/{caption}
    defaults: { _controller: LaLearnodexBundle:Trace:traceButton }
url_trace:
    path:     /urltrace/{id}
    defaults: { _controller: LaLearnodexBundle:Trace:traceUrl }
dna:
    path:     /dna
    defaults: { _controller: LaLearnodexBundle:Default:dna }
remove_all_my_traces:
    path:     /removeallmytraces
    defaults: { _controller: LaLearnodexBundle:Trace:removeMyTraces }

admin_homepage:
    path:     /admin
    defaults: { _controller: LaLearnodexBundle:Admin:index }
new_card:
    path:     /admin/new/{type}
    defaults: { _controller: LaLearnodexBundle:Admin:new }
card_name:
    path:     /admin/name/{id}
    defaults: { _controller: LaLearnodexBundle:Admin:name }
card_content_select:
    path:     /admin/content/select/{id}
    defaults: { _controller: LaLearnodexBundle:Admin:selectContent }
card_content_selected:
    path:     /admin/content/select/{id}/{type}
    defaults: { _controller: LaLearnodexBundle:Admin:selectContent }
card_content:
    path:     /admin/content/{id}
    defaults: { _controller: LaLearnodexBundle:Admin:content }
add_answer:
    path:     /admin/addAnswer/{id}
    defaults: { _controller: LaLearnodexBundle:Admin:addAnswer }
remove_answer:
    path:     /admin/removeAnswer/{id}/{answerId}
    defaults: { _controller: LaLearnodexBundle:Admin:removeAnswer }
card_outcome:
    path:     /admin/entity/{id}/outcome
    defaults: { _controller: LaLearnodexBundle:Admin:outcome }
add_outcome:
    path:     /admin/addoutcome/{id}
    defaults: { _controller: LaLearnodexBundle:Admin:addOutcome }
set_outcome_affinity:
    path:     /admin/setoutcomeaffinity/{outcomeId}/{affinity}
    defaults: { _controller: LaLearnodexBundle:Admin:setOutcomeAffinity }
set_outcome_progress:
    path:     /admin/setoutcomeprogress/{outcomeId}/{progress}
    defaults: { _controller: LaLearnodexBundle:Admin:setOutcomeProgress }
remove_outcome:
    path:     /admin/removeoutcome/{outcomeId}
    defaults: { _controller: LaLearnodexBundle:Admin:removeOutcome }
add_result:
    path:     /admin/addresult/{id}/{outcomeId}
    defaults: { _controller: LaLearnodexBundle:Admin:addResult }
set_result:
    path:     /admin/setresult/{resultId}/{value}
    defaults: { _controller: LaLearnodexBundle:Admin:setResult }
remove_result:
    path:     /admin/removeresult/{resultId}
    defaults: { _controller: LaLearnodexBundle:Admin:removeResult }

card_link:
    path:     /admin/entity/{id}/link
    defaults: { _controller: LaLearnodexBundle:Admin:link }
add_link:
    path:     /admin/addLink/{id}/{parentId}/{childId}
    defaults: { _controller: LaLearnodexBundle:Admin:addLink }
edit_link:
    path:     /admin/editLink/{id}/{linkId}
    defaults: { _controller: LaLearnodexBundle:Admin:editLink }
remove_link:
    path:     /admin/removeLink/{id}/{linkId}
    defaults: { _controller: LaLearnodexBundle:Admin:removeLink }

manage_user_roles:
    path:     /admin/users
    defaults: { _controller: LaLearnodexBundle:Admin:users }
make_admin:
    path:     /admin/users/makeAdmin/{id}
    defaults: { _controller: LaLearnodexBundle:Admin:makeAdmin }
make_user:
    path:     /admin/users/makeUser/{id}
    defaults: { _controller: LaLearnodexBundle:Admin:makeUser }

goal_create_agora:
    path:     /goal/create/agora/{id}
    defaults: { _controller: LaLearnodexBundle:Goal:createAgoraGoal }
goal_remove:
    path:     /goal/remove/{id}
    defaults: { _controller: LaLearnodexBundle:Goal:removeGoal }
goal_open:
    path:     /goal/open/{id}
    defaults: { _controller: LaLearnodexBundle:Goal:open }
goal_close:
    path:     /goal/close
    defaults: { _controller: LaLearnodexBundle:Goal:close }


clear_database:
    path:     /cleardb
    defaults: { _controller: LaLearnodexBundle:Import:clearDatabase }
set_database_1:
    path:     /setdb1
    defaults: { _controller: LaLearnodexBundle:Import:newDatabase1 }
onderwijskiewer_database:
    path:     /owkdb
    defaults: { _controller: LaLearnodexBundle:Import:onderwijsKiezer }
