homepage:
    path:     /
    defaults: { _controller: LaLearnodexBundle:Default:index }

register:
    path:     /register
    defaults: { _controller: LaLearnodexBundle:User:register }
login:
    path:     /login
    defaults: { _controller: LaLearnodexBundle:User:login }
login_check:
    path:     /login_check
logout:
    path:     /logout

card:
    path:     /card/{id}
    defaults: { _controller: LaLearnodexBundle:Card:index }

new_card:
    path:     /new/{type}
    defaults: { _controller: LaLearnodexBundle:Admin:new }
card_name:
    path:     /name/{id}
    defaults: { _controller: LaLearnodexBundle:Admin:name }
card_content_select:
    path:     /content/select/{id}
    defaults: { _controller: LaLearnodexBundle:Admin:selectContent }
card_content_selected:
    path:     /content/select/{id}/{type}
    defaults: { _controller: LaLearnodexBundle:Admin:selectContent }
card_content:
    path:     /content/{id}
    defaults: { _controller: LaLearnodexBundle:Admin:content }
card_outcome:
    path:     /entity/{id}/outcome
    defaults: { _controller: LaLearnodexBundle:Admin:outcome }
add_outcome:
    path:     /addoutcome/{id}
    defaults: { _controller: LaLearnodexBundle:Admin:addOutcome }
update_outcome:
    path:     /updateoutcome/{outcomeId}
    defaults: { _controller: LaLearnodexBundle:Admin:updateOutcome }
remove_outcome:
    path:     /removeoutcome/{outcomeId}
    defaults: { _controller: LaLearnodexBundle:Admin:removeOutcome }

card_link:
    path:     /entity/{id}/link
    defaults: { _controller: LaLearnodexBundle:Admin:link }
add_child:
    path:     /addChild/{parentId}/{childId}
    defaults: { _controller: LaLearnodexBundle:Admin:addChild }
