parameters:
    la_learnodex.model.card.class: La\LearnodexBundle\Model\Card

services:
#    la_learnodex.example:
#        class: %la_learnodex.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
