La\CoreBundle\Entity\Affinity:
    repositoryClass: La\CoreBundle\Entity\Repository\AffinityRepository
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        value:
            type: decimal
            precision: '5'
            scale: '2'
    manyToOne:
        user:
            targetEntity: User
            inversedBy: affinities
            joinColumn:
                name: user_id
                referencedColumnName: id
        agora:
            targetEntity: Agora
            inversedBy: affinities
            joinColumn:
                name: agora_id
                referencedColumnName: id
        profile:
            targetEntity: Profile
            joinColumn:
                name: profile_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
