La\CoreBundle\Entity\AgoraBase:
    repositoryClass: La\CoreBundle\Entity\Repository\AgoraBaseRepository
    type: entity
    table: null
    oneToMany:
        goals:
            targetEntity: Goal
            mappedBy: agora
    lifecycleCallbacks: {  }
