La\CoreBundle\Entity\Content:
    type: entity
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discr
        type: string
        length: 16
    discriminatorMap:
        html: HtmlContent
        url: UrlContent
        question: QuestionContent
        mcq: MultipleChoiceQuestion
        simple: SimpleQuestion
        urlsimple: SimpleUrlQuestion
        quiz: QuizContent
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
