La\CoreBundle\Entity\Goal:
    type: entity
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discr
        type: string
        length: 16
    discriminatorMap:
        agora: AgoraGoal
        persona: PersonaGoal
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        user:
            targetEntity: User
            inversedBy: goals
            joinColumn:
                name: user_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
