La\CoreBundle\Entity\LearningEntity:
    type: entity
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discr
        type: string
        length: 16
    discriminatorMap:
        agora: Agora
        objective: Objective
        action: Action
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
    oneToMany:
        outcomes:
            targetEntity: Outcome
            mappedBy: learningEntity
    manyToOne:
        owner:
            targetEntity: User
            inversedBy: learningEntities
            joinColumn:
                name: owner_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
