La\CoreBundle\Entity\LearningEntity:
    repositoryClass: La\CoreBundle\Entity\Repository\LearningEntityRepository
    type: entity
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discr
        type: string
        length: 16
    discriminatorMap:
        agora: Agora
        objective: Objective
        action: Action
        phronesis: Phronesis
        techne: Techne
        domain: Domain
        logos: Logos
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    oneToOne:
        content:
            targetEntity: Content
            joinColumn:
                name: content_id
                referencedColumnName: id
    oneToMany:
        outcomes:
            targetEntity: Outcome
            mappedBy: learningEntity
        uplinks:
            targetEntity: Uplink
            mappedBy: child
        downlinks:
            targetEntity: Uplink
            mappedBy: parent
        progress:
            targetEntity: Progress
            mappedBy: learningEntity
        userProbabilities:
            targetEntity: UserProbability
            mappedBy: learningEntity
    manyToOne:
        owner:
            targetEntity: User
            inversedBy: learningEntities
            joinColumn:
                name: owner_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
