La\CoreBundle\Entity\Lom:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        instruction:
            type: text
        url:
            type: string
            length: 255
    manyToOne:
        learningContent:
            targetEntity: LearningContent
            inversedBy: loms
            joinColumn:
                name: learning_content_id
                referencedColumnName: id
    oneToMany:
        outcomes:
            targetEntity: LearningOutcome
            mappedBy: lom
    lifecycleCallbacks: {  }
