La\CoreBundle\Entity\Outcome:
    type: entity
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: subject
        type: string
        length: 16
    discriminatorMap:
        affinity: AffinityOutcome
        answer: AnswerOutcome
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        learningEntity:
            targetEntity: LearningEntity
            inversedBy: outcomes
            joinColumn:
                name: learning_entity_id
                referencedColumnName: id
    oneToMany:
        results:
            targetEntity: Result
            mappedBy: outcome
    lifecycleCallbacks: {  }
