La\CoreBundle\Entity\Outcome:
    type: entity
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: subject
        type: string
        length: 16
    discriminatorMap:
        affinity: AffinityOutcome
        answer: AnswerOutcome
        button: ButtonOutcome
        url: UrlOutcome
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        affinity:
            type: integer
            nullable: true
        progress:
            type: integer
            nullable: true
    manyToOne:
        learningEntity:
            targetEntity: LearningEntity
            inversedBy: outcomes
            joinColumn:
                name: learning_entity_id
                referencedColumnName: id
    oneToMany:
        traces:
            targetEntity: Trace
            mappedBy: outcome
        probabilities:
            targetEntity: ProbabilityGivenProfile
            mappedBy: outcome
    lifecycleCallbacks: {  }
