La\CoreBundle\Entity\Persona:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        description:
            type: text
    oneToOne:
        user:
            targetEntity: User
            joinColumn: user_id
            referencedColumnName: id
    oneToMany:
        users:
            targetEntity: PersonaMatch
            mappedBy: persona
        goals:
            targetEntity: Goal
            mappedBy: persona
    lifecycleCallbacks: {  }
