La\CoreBundle\Entity\ProbabilityGivenProfile:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        probability:
            type: decimal
            precision: '5'
            scale: '2'
    manyToOne:
        outcome:
            targetEntity: Outcome
            joinColumn:
                name: outcome_id
                referencedColumnName: id
        profile:
            targetEntity: Profile
            joinColumn:
                name: profile_id
                referencedColumnName: id

    lifecycleCallbacks: {  }
