La\CoreBundle\Entity\QuestionContent:
    type: entity
    table: null
    fields:
        instruction:
            type: text
        question:
            type: text
    oneToMany:
        answers:
            targetEntity: Answer
            mappedBy: question
    lifecycleCallbacks: {  }
