La\CoreBundle\Entity\Result:
    type: entity
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: type
        type: string
        length: 16
    discriminatorMap:
        affinity: AffinityResult
        nextentity: NextEntityResult
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        value:
            type: integer
    manyToOne:
        outcome:
            targetEntity: Outcome
            inversedBy: results
            joinColumn:
                name: outcome_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
