La\CoreBundle\Entity\Trace:
    repositoryClass: La\CoreBundle\Entity\Repository\TraceRepository
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdTime:
            type: datetime
            column: created_time
    manyToOne:
        user:
            targetEntity: User
            inversedBy: traces
            joinColumn:
                name: user_id
                referencedColumnName: id
        outcome:
            targetEntity: Outcome
            inversedBy: traces
            joinColumn:
                name: outcome_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
