La\CoreBundle\Entity\User:
    type: entity
    table: fos_user

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    oneToMany:
        learningEntities:
            targetEntity: LearningEntity
            mappedBy: owner
        traces:
            targetEntity: Trace
            mappedBy: user
        affinities:
            targetEntity: Affinity
            mappedBy: user
        progress:
            targetEntity: Progress
            mappedBy: user
        personas:
            targetEntity: PersonaMatch
            mappedBy: user
        goals:
            targetEntity: Goal
            mappedBy: user
