La\CoreBundle\Entity\UserProbabilityEvent:
    repositoryClass: La\CoreBundle\Entity\Repository\UserProbabilityEventRepository
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        message:
            type: string
        threshold:
            type: integer
        seen:
            type: boolean
        removed:
            type: boolean
        createdOn:
            type: datetime
            column: created_on
    manyToOne:
        userProbability:
            targetEntity: UserProbability
            inversedBy: events
            joinColumn:
                name: user_probability_id
                referencedColumnName: id
                onDelete: Cascade
    lifecycleCallbacks: {  }
